run:
  go: '1.18'
  skip-dirs:
    - "mnt/"
    - "old-image/"
  skip-files:
    - "mnt/*"
    - "old-image/*"
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - depguard
    - dupl
    - gocognit
    - gocritic
    - gocyclo
    - goconst
    - goimports
    - gosec