run:
  go: '1.18'
linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - depguard
    - dupl
    - gocognit
    - gocritic
    - gocyclo
    - goconst
    - goimports
    - gosec